resource_types:
- name: release-resource
  type: docker-image
  source:
    repository: ssoerensen/release-manager-resource
    tag: latest

resources:
  - name: push-successfull-build
    type: release-resource
    source:
      uri: 'http://172.18.0.1:9191/'
      application: test-application
      step: build

  - name: release-to-prod-version
    type: release-resource
    source:
      uri: 'http://172.18.0.1:9191/'
      application: test-application
      step: prod


  - name: source-code
    type: git
    source:
      uri: https://github.com/ssoerensen/concourse.git
      branch: master

jobs:
  - name: step-1
    plan:
      - get: source-code
        trigger: true

      - task: task-version
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: source-code
          outputs:
            - name: tag
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                find ./
                date > tag/current-tag
                cat tag/current-tag
                find ./

      - task: task-1
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                find ./
                echo "Doing some cool stuff"

      - put: push-successfull-build
        params: { next-stage: staging }


  - name: release-to-prod
    plan:
      - get: push-successfull-build
        passed: [ step-1 ]
        trigger: false
      - get: release-to-prod-version
        trigger: true
      - task: task-1
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: release-to-prod-version
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                find ./
                echo "Doing some cool stuff"
