#!/usr/bin/env bash

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

json=$(tee)
host=$(echo $json | jq -r '.source.uri')

env
echo "PUT and SEARCH"
echo $1
find $1
echo "SEARCH ./"
find ./
echo "DONE"
pwd

echo "Request: ${host}/check (check)"
# echo "Current Tag:"
# cat $1/tag/current-tag

echo $json | jq "."
echo $json | curl -H 'Accept: application/json' -H "Content-Type: application/json" -X PUT -d @- ${host}/check >&3