#!/usr/bin/env bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

json=$(tee)
host=$(echo $json | jq -r '.source.uri')

env
echo $1
find $1
find ./
pwd


echo "Request: ${host}/fetch (in)"
echo $json | jq "."
resp=$(echo $json | curl -H 'Accept: application/json' -H "Content-Type: application/json" -X PUT -d @- ${host}/fetch)
mkdir -p $1/tag
echo $resp | jq ".version.ref" > $1/tag/current-tag
echo $resp | jq ".version.ref" > $1/current-tag

env
echo $1
find $1
find ./
pwd

echo ${resp} |jq "." >&3
